apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: patient-monitoring
type: Opaque
stringData:
  username: postgres_dev
  password: dev_password_example  # In real scenario, this would be replaced by a CI/CD pipeline