apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-rolebinding
  namespace: patient-monitoring
subjects:
- kind: ServiceAccount
  name: postgres-sa
  namespace: patient-monitoring
roleRef:
  kind: Role
  name: postgres-role
  apiGroup: rbac.authorization.k8s.io