apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- postgres-pvc.yaml
- networkpolicy.yaml
- rbac/role.yaml
- rbac/rolebinding.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/part-of: patient-monitoring
  app.kubernetes.io/managed-by: kustomize